"""Centralized ticker context keywords and disambiguation helpers."""

ticker_context = {
    "A": ["agilent", "lab equipment", "chromatography", "analytical instruments", "keysight spinoff"],
    "B": ["barnes group", "aerospace machining", "mro"],
    "C": ["citigroup", "citi", "consumer banking", "investment bank"],
    "D": ["dominion", "utility", "power generation", "natural gas", "pipeline"],
    "E": ["eni", "italian energy", "oil", "gas"],
    "F": ["ford", "f-150", "mustang", "bronco", "detroit auto"],
    "G": ["genpact", "bpo", "business process", "outsourcing"],
    "H": ["hyatt", "hotel", "hospitality", "lodging"],
    "K": ["kellogg", "kellanova", "cereal", "snacks"],
    "L": ["loews", "conglomerate", "insurance", "pipeline"],
    "M": ["macys", "department store", "retail"],
    "O": ["realty income", "reit", "monthly dividend", "triple net"],
    "R": ["ryder", "truck rental", "logistics", "fleet management"],
    "T": ["at&t", "wireless", "fiber", "telecom"],
    "U": ["unity", "game engine", "monetization", "runtime"],
    "X": ["us steel", "steelmaker", "hot rolled", "steel industry"],
    "V": ["visa inc", "visa payments", "payments network", "card network", "global payments", "interchange fees", "transaction volume", "payment processing", "merchant acceptance", "cross border payments", "cross border volume", "payment rails", "issuer bank", "acquirer bank", "digital payments", "contactless payments", "tokenization", "fintech partnerships", "regulatory scrutiny", "antitrust", "fees regulation", "earnings", "revenue growth", "operating margin", "dividend", "buyback", "al kelly", "ryan mckinerney"],
    "AC": ["air canada", "canadian airline", "toronto", "montreal", "vancouver"],
    "AAPL": ["apple", "iphone", "ipad", "mac", "macbook", "ipad pro"],
    "ADBE": ["adobe", "creative cloud", "digital media", "subscription", "generative ai"],
    "ADP": ["automatic data processing", "payroll", "hr software"],
    "AEO": ["american eagle", "apparel", "teen fashion", "mall retail", "denim"],
    "ALAB": ["astera labs", "cxl", "ai networking", "pcie"],
    "ANET": ["arista", "networking", "switches", "datacenter", "ethernet", "ai infrastructure"],
    "ANF": ["abercrombie", "fitch", "retail", "mall retail", "turnaround", "denim"],
    "APLD": ["applied digital", "data centers", "hpc", "ai hosting", "colocation"],
    "ASTS": ["ast spacemobile", "satellite", "direct to device", "space-based cellular", "telecom partnerships"],
    "AVGO": ["broadcom", "semiconductors", "chips", "ai accelerators", "custom silicon", "networking hardware", "data center"],
    "BA": ["boeing", "aerospace", "defense", "commercial aviation", "launch systems"],
    "BABA": ["alibaba", "china ecommerce", "hangzhou", "ali cloud", "jack ma"],
    "BE": ["bloom energy", "fuel cell", "solid oxide", "power server", "hydrogen"],
    "BK": ["bk technologies", "land mobile radios", "defense communications", "insider ownership"],
    "BILI": ["bilibili", "china streaming", "anime", "video platform"],
    "BEST": ["best inc", "best logistics", "china logistics", "delivery services"],
    "BMNR": ["ethereum", "validator network", "staking", "tokenization"],
    "BUD": ["anheuser", "inbev", "budweiser", "beer", "alcohol", "beverage", "beyond beer", "beatbox"],
    "CLS": ["celestica", "electronics manufacturing", "contract manufacturing", "hardware services"],
    "CORZ": ["core scientific", "bitcoin mining", "data centers", "hosting", "hash rate"],
    "CRWD": ["crowdstrike", "endpoint", "falcon", "cybersecurity", "edr", "xdr", "threat hunting"],
    "CVNA": ["carvana", "used cars", "online auto sales", "auto ecommerce", "subprime loans", "inventory", "vending machine"],
    "DASH": ["doordash", "delivery", "food delivery", "courier", "dashpass", "ubereats", "grubhub", "restaurant delivery"],
    "DBX": ["dropbox", "cloud storage", "file sync", "saas"],
    "DKNG": ["draftkings", "sports betting", "gambling"],
    "DLTR": ["dollar tree", "discount retailer", "value chain"],
    "DNOW": ["distributionnow", "oilfield services", "industrial distribution", "energy equipment"],
    "EDU": ["new oriental", "education", "china tutoring"],
    "EDIT": ["editas", "gene editing", "crispr", "biotech"],
    "ESNT": ["essent", "mortgage insurance", "private mortgage", "bermuda", "home loans"],
    "EVTL": ["vertical aerospace", "evtol", "electric aviation", "urban air mobility"],
    "FIGR": ["figure technologies", "blockchain lending", "mortgage tech", "tokenization", "provenance"],
    "FLNC": ["fluence energy", "energy storage", "grid software", "battery systems"],
    "FLWS": ["1-800-flowers", "gifting", "ecommerce", "floral delivery", "seasonal demand"],
    "FLOT": ["floating rate", "bond etf", "treasury", "investment grade", "short term bond"],
    "GME": ["gamestop", "ryan cohen", "stonks", "moass", "retail trader"],
    "GOOG": ["google", "alphabet", "search", "youtube", "gemini"],
    "GOLD": ["barrick", "barrick gold", "mining", "ounces", "commodity","goldcorp", "newmont"],
    "GS": ["goldman sachs", "investment banking", "research notes", "macro outlook"],
    "HOOD": ["robinhood", "brokerage", "trading app", "vlad tenev"],
    "HSBC": ["hsbc", "global bank", "international banking", "wealth management"],
    "IBM": ["ibm", "quantum computing", "enterprise software", "hardware systems"],
    "IBIT": ["blackrock", "bitcoin etf", "spot bitcoin", "crypto fund"],
    "IP": ["international paper", "pulp", "packaging", "paper products"],
    "IMO": ["imperial oil", "oil sands", "upstream", "refining", "canadian energy"],
    "IOVA": ["iova", "biotech", "til therapy", "lifileucel", "melanoma","cell therapy", "oncology"],
    "IREN": ["iris energy", "bitcoin miner", "data center", "ai infrastructure"],
    "IWM": ["russell 2000", "small cap etf", "market breadth", "small cap rally"],
    "JPM": ["jpmorgan", "jpmorgan chase", "jp morgan", "chase bank", "investment bank", "banking", "asset management", "commercial banking", "consumer banking", "credit cards", "wealth management", "treasury services", "capital markets", "jamie dimon", "ceo", "wall street", "new york", "tariffs", "macro outlook"],
    "KEX": ["kirby corporation", "barge", "inland marine", "tugboat", "marine transportation", "petrochemical transport"],
    "KRMN": ["karman", "aerospace manufacturing", "defense contracting", "hypersonics"],
    "KSS": ["kohls", "department store", "apparel", "inventory", "promotions"],
    "LLY": ["eli lilly", "mounjaro", "zepbound", "pharma", "weight loss drug"],
    "LMT": ["lockheed martin", "defense", "prime contractor", "missile systems", "space launch"],
    "LSEG": ["london stock exchange", "exchange group", "ftse owner"],
    "LUNR": ["intuitive machines", "lunar", "moon mission", "nasa contracts", "lunar lander"],
    "LVMH": ["louis vuitton", "moet hennessy", "bernard arnault", "luxury conglomerate"],
    "META": ["meta", "facebook", "instagram", "whatsapp", "oculus", "vr", "metaverse", "threads", "zuck", "zuckerberg"],
    "MRVL": ["marvell", "semiconductors", "data center chips", "networking silicon", "ai accelerators"],
    "MSCI": ["index provider", "benchmark", "indices"],
    "MSFT": ["microsoft", "azure", "cloud computing", "windows", "xbox", "copilot", "satya nadella", "enterprise software", "hyperscaler", "ai infrastructure", "data centers", "gpu spend", "nvidia chips", "capital expenditures", "free cash flow", "operating income", "valuation", "earnings", "guidance"],
    "MSTR": ["microstrategy", "michael saylor", "bitcoin", "btc treasury", "convertible notes"],
    "MT": ["arcelormittal", "steel", "iron ore", "steel mills", "trade tariffs"],
    "MYRG": ["myr group", "electrical contracting", "grid infrastructure"],
    "NTDOY": ["nintendo", "gaming", "console", "wii", "switch", "zelda", "pokemon", "mario", "nintendo switch", "kirby"],
    "NBIS": ["nasdaq biotech etf", "biotech exposure", "clinical pipeline", "healthcare sector"],
    "NEE": ["nextera", "utility", "renewable energy", "florida power", "fpl"],
    "NICE": ["nice ltd", "nice systems", "cxone", "contact center", "contact center software", "customer experience", "cx software", "call center", "workforce management", "wfm", "quality management", "interaction analytics", "speech analytics", "financial crime", "aml compliance", "fraud detection", "regulatory compliance", "risk management", "enterprise saas", "cloud platform", "customer analytics", "israel", "raanana"],
    "NKE": ["nike", "footwear", "athletic apparel", "sneakers", "endorsements"],
    "NQ": ["nasdaq futures", "e-mini", "index futures", "/nq", "nasdaq 100"],
    "NUE": ["nucor", "steel", "electric arc furnace", "infrastructure spending"],
    "NVDA": ["nvidia", "geforce", "rtx", "cuda", "gpu", "jensen", "chips", "semiconductor", "data center", "taiwan"],
    "NXXT": ["microgrids", "distributed energy", "localized grid"],
    "OKLO": ["nuclear", "microreactor", "oklo"],
    "ORCL": ["oracle", "cloud infrastructure", "oci", "database", "enterprise software"],
    "PATH": ["uipath", "automation", "rpa", "robotic process automation", "maestro"],
    "PDD": ["pinduoduo", "temu", "china ecommerce"],
    "PHYS": ["sprott", "gold trust"],
    "PL": ["planet labs", "earth imaging", "satellites", "geospatial data", "analytics"],
    "PLD": ["prologis", "reit", "logistics", "warehouses"],
    "PPSI": ["pioneer power", "microgrids", "distributed infrastructure"],
    "QQQ": ["nasdaq 100", "tech index", "nasdaq"],
    "RBC": ["royal bank of canada", "wealth management", "capital markets"],
    "SWCH": ["switch inc", "data centers", "colocation", "prime data centers"],
    "RGTI": ["rigetti", "quantum", "kulkarni", "rigetti computing"],
    "RGTZ": ["rigetti", "inverse", "quantum"],
    "RKLB": ["rocket lab", "launch", "electron rocket", "neutron", "space missions"],
    "SEZL": ["sezzle", "bnpl", "installments", "credit", "buy now pay later"],
    "SGOV": ["t bill", "treasury etf", "short term treasury", "government bond", "cash alternative"],
    "SMR": ["small modular reactor", "nuclear"],
    "SOND": ["sonder", "hospitality", "lodging"],
    "SPY": ["s&p 500", "index fund", "sp500", "benchmark", "market index", "large cap", "passive investing", "expense ratio"],
    "TAL": ["tal education", "tutoring", "china education", "edtech"],
    "TQQQ": ["3x leveraged etf", "nasdaq 100 leverage", "daily reset", "volatility"],
    "TISI": ["team inc", "industrial services", "maintenance", "inspection", "repair"],
    "TSLA": ["tesla", "tesla inc", "elon", "elon musk", "musk", "electric vehicles", "ev maker", "gigafactory", "autopilot", "full self driving", "fsd", "cybertruck", "model s", "model 3", "model x", "model y", "robotaxi", "self driving", "ai driving", "battery technology", "4680 battery", "energy storage", "megapack", "powerwall", "solar", "tesla energy", "supercharger", "charging network", "deliveries", "vehicle margins", "austin", "texas"],
    "URBN": ["urban outfitters", "anthropologie", "free people", "fashion", "retail"],
    "URA": ["uranium etf", "miners"],
    "UUUU": ["energy fuels", "uranium", "rare earths"],
    "VEQT": ["vanguard all equity", "all equity etf", "veqt.to"],
    "VGSH": ["vanguard", "short term treasury", "treasury etf", "bond fund"],
    "VHYG": ["vanguard usd", "corporate bond", "high yield bond", "vhyg.l"],
    "VOO": ["s&p 500 exposure", "vanguard etf", "low expense ratio", "passive"],
    "VRT": ["vertiv", "data center infrastructure", "thermal management", "power systems"],
    "VTI": ["total stock market", "vanguard", "broad market etf", "us equities", "passive investing", "portfolio allocation", "vxus"],
    "VXUS": ["vanguard international", "ex-us", "international equities", "global diversification"],
    "WB": ["weibo", "china social media", "microblog"],
    "WBD": ["warner", "discovery", "hbo", "max", "netflix", "studio deal", "streaming", "content distribution"],
    "WSR": ["whitestone reit", "shopping centers", "retail reit", "houston", "phoenix"],
    "WRBY": ["warby parker", "eyeglasses", "eyewear", "direct to consumer", "vision care"],
    "DRIP": ["direxion", "oil", "etf", "oil futures"],
    "TLN": ["talen energy corp", "natural gas", "pipeline", "power generation", "utility"],
    "RSI": ["rush street interactive", "gambling", "casino", "sports betting", "online gaming", "bet rivers", "rush bet", "rushbet.co", "sugarhouse"],
    "HLX": ["helix energy solutions group", "energy", "oil", "gas", "pipeline", "power generation", "utility"],
    "DELL": ["dell technologies", "computer", "laptop", "desktop", "server", "data center", "storage", "networking", "security"],
    "CAN": ["canaan", "supercomputing", "performance", "bitcoing mining", "chip design", "chip", "hardware", "chip research"],
    "HBM": ["hudbay", "metals", "toronto", "mining", "minerals", "smelting", "copper", "gold", "silver", "zinc"],
    "HPQ": ["hewlett packard enterprise", "enterprise software", "cloud computing", "hp", "palo alto", "printers"], 
    "ICE": ["intercontinental exchange", "exchange", "trading", "futures", "options", "commodities", "currency", "fx", "macro"],
    "MGX": ["genetics", "genome", "pharmaceuticals", "therapeutics", "biotechnology", "genetic testing", "genetic analysis", "genetic sequencing", "genetic profiling", "genetic prediction", "genetic diagnosis", "genetic treatment", "genetic therapy", "genetic engineering", "genetic modification", "genetic engineering", "genetic modification"],
    "FOXA": ["fox news", "fox corporation", "reports", "media group", "media", "network"],
    "TGT": ["target", "retail", "department store", "apparel", "consumer goods", "discount retailer", "value chain", "red", "walmart", "costco", "kroger"],
    "SNDL": ["cannabis", "marijuana", "weed", "calgary", "liquor", "alcohol", "ace liquor", "wine and beyond", "liquor depot", "spiritleaf", "firesale cannabis", "small-batch"],
    "HHS": ["harte hanks"],
    "WLTH": ["wealthfront", "financial services", "andy rachleff", "dan carroll", "automated investing", "fintech", "robo-advisory", "wealth-management"],
    "TST": ["toast", "cloud", "POS", "point-of-sale", "android", "ordering", "restaurant", "kitchen", "delivery", "mobile order"],
    "RSI": ["rush street interactive", "gambling", "casino", "sports betting", "online gaming", "bet rivers", "rush bet", "rushbet.co", "sugarhouse"],
    "SILJ": ["silver", "silver etf", "silver mining", "silver bullion", "silver investment", "silver trading", "silver market", "silver futures", "silver options", "silver futures", "silver options"],
    "MYNZ": ["mainz", "biomed", "coloalert", "medicaid", "medicine", "healthcare", "diagnostics"],
    "DNA": ["ginkgo", "bioworks", "genetics", "bacteria", "vaccine", "immunology", "genetic testing", "genetic analysis", "genetic sequencing", "genetic profiling", "genetic prediction", "genetic diagnosis", "genetic treatment", "genetic therapy", "genetic engineering", "genetic modification", "genetic engineering", "genetic modification"],
    "CRC": ["california resources", "berry", "energy", "carbon management", "environment", "terravault"],
    "UVV": ["tobacco", "nicotine", "vaping"],
    "RIME": ["algorhythm", "saas", "ai"],
    "GEV": ["ge", "vernova", "energy", "manufacturing", "massachusetts", "scott strazik", "electricity", "wind", "turbines", "ken parks"],
    "AVGO": ["broadcom", "semiconductors", "chips", "ai accelerators", "custom silicon", "networking hardware", "data center", "silicon", "cloud computing", "infrastructure"],
    "GES": ["clothing", "denim", "accessories", "fashion", "retail", "marciano", "jeans"],
    "SMCI": ["microchip", "microcomputer", "it", "enterprise", "server", "storage"],
    "AGI": ["alamos gold", "gold", "mining", "minerals"],
    "ON": ["onsemi", "on semiconductor", "on semi", "power semiconductor", "power chips", "silicon carbide", "sic", "automotive chips", "ev chips", "ev inverter", "power management", "mosfet", "igbt", "power modules", "charging systems", "vehicle electrification", "hassane el khoury", "scottsdale", "arizona"],
    "ALL": ["allstate", "insurance", "property", "glennview", "personal lines", "auto insurance", "homeowners insurance", "renters insurance"],
    "GTX": ["garrett motion", "motion", "automotive"],
    "TSM": ["tsmc", "semiconductor", "taiwan", "manufacturing", "chip", "chips", "silicon", "cloud computing", "infrastructure", "fabrication", "plant"],
    "INTC": ["intel", "semiconductor", "chip", "chips", "silicon", "cloud computing", "infrastructure", "fabrication", "plant"],
    "AWRE": ["aware inc", "aware", "biometric software", "identity verification", "authentication software", "facial recognition", "fingerprint recognition", "cambridge", "massachusetts", "ajay amlani", "brian krause"],
    "CGNX": ["cognex", "machine vision", "vision systems", "vision software", "vision hardware", "industrial vision", "factory vision", "ai vision", "deep learning vision", "robert willett", "natick", "massachusetts"],
    "ZBRA": ["zebra technologies", "zebra tech", "warehouse automation", "barcode", "barcode scanner", "barcode scanning", "rfid", "inventory tracking", "supply chain", "logistics", "industrial automation", "asset tracking", "mobile computers", "handheld scanners", "pos", "point of sale", "manufacturing automation", "distribution center", "warehouse management", "wms", "anders gustafsson", "lincolnshire", "illinois"],
    "AZTA": ["azenta", "azenta inc", "life-science automation", "life sciences", "biorepository", "biobanking", "sample management", "cold storage", "cryogenic storage", "lab automation", "laboratory automation", "genomics", "drug discovery", "clinical trials", "biotech", "pharma", "biopharma", "biospecimen", "sample tracking", "temperature controlled storage", "steve schwartz", "burlington", "massachusetts"],
    "PTC": ["ptc", "ptc software", "industrial software", "digital twin", "digital twins", "industrial iot", "manufacturing software", "plm", "cad", "thingworx", "windchill", "jim heppelmann", "boston"],
    "WLDS": ["wlds", "ishares", "world small cap", "small cap etf", "global small cap", "international small cap", "equity etf", "index fund", "msci", "portfolio allocation", "asset allocation"],
    "IVV": ["ivv", "ishares", "sp500", "s&p 500", "s&p500", "index etf", "market index", "large cap", "us equities", "expense ratio", "long term investing", "buy and hold", "passive investing", "portfolio allocation"],
    "SPT": ["sprout social", "sprout", "social media software", "marketing saas", "social analytics", "social listening", "brand management", "insider buying", "insider purchase", "aaron rankin", "justyn howard", "ryan bartholomew", "chicago", "enterprise social", "marketing tech"],
    "ALB": ["albemarle", "lithium", "lithium producer", "battery materials", "ev batteries", "energy storage", "spodumene", "lithium brine", "preferred stock", "convertible preferred", "alb-a", "dividends", "options strategy", "covered call", "chile", "australia"],
    "MORN": ["morningstar", "morningstar inc", "investment research", "fund ratings", "star ratings", "analyst ratings", "etf ratings", "mutual fund ratings", "credit risk", "liquidity risk", "fund analysis", "portfolio analysis", "investment data", "research firm", "moat ratings", "economic moat", "chicago"],
    "FSLR": ["first solar", "first solar inc", "solar", "utility scale solar", "solar panels", "solar manufacturing", "thin film", "cadmium telluride", "cdte", "renewable energy", "clean energy", "solar farms", "power generation", "grid scale", "us manufacturing", "energy transition", "ira credits", "tax credits", "arizona"],
    "OR": ["osisko", "osisko royalties", "gold royalties", "royalty company", "precious metals royalties", "gold streaming", "mining royalties", "royalty portfolio", "streaming agreements", "cash flow royalties", "canadian miner", "montreal", "malartic", "canadian malartic", "sean roosen", "royalty model", "gold production exposure"],
    "ALLY": ["ally", "ally bank", "ally financial", "online bank", "savings account", "high yield savings", "checking account", "auto loans", "auto lending", "digital banking", "interest rate", "aprs", "consumer finance", "detroit"],
    "ANY": ["sphere 3d", "sphere 3d corp", "bitcoin mining", "crypto mining", "btc mining", "hashrate", "miners", "blockchain", "mining rigs", "datacenter", "energy costs", "hosting agreement", "north america mining"],
    "NNI": ["nelnet", "nelnet inc", "student loan servicing", "education technology", "loan servicing", "loan origination", "payment processing", "tuition management", "campus commerce", "facts brand", "education payments", "asset management", "nelnet bank", "lincoln nebraska", "renewable energy investments", "real estate investments", "venture capital", "dividend", "financial services", "education finance", "school systems", "payment technology", "student loans"],
    "TISI": ["team inc", "team industrial services", "industrial services", "inspection services", "maintenance services", "repair services", "nondestructive testing", "ndt", "asset integrity", "plant maintenance", "industrial safety", "shutdown services", "turnaround services", "heat treating", "bolting services", "leak repair", "pipeline inspection", "refinery services", "petrochemical", "power plants", "energy infrastructure", "executive team", "field services", "industrial contracting", "houston", "texas"],
    "EDIT": ["editas", "editas medicine", "crispr", "gene editing", "cas9", "genome editing", "biotechnology", "biotech", "genetic therapy", "in vivo editing", "cell therapy", "clinical trial", "pipeline update", "intellia", "crispr therapeutics", "beam therapeutics", "cambridge", "massachusetts"],
    "HR": ["healthcare realty", "healthcare realty trust", "healthcare reit", "medical office buildings", "mob reit", "medical office", "outpatient facilities", "healthcare properties", "physician offices", "hospital affiliated", "reit dividend", "lease occupancy", "property portfolio", "healthcare real estate", "merger", "htaw merger", "nashville", "tennessee"],
    "TILE": ["interface inc", "interface flooring", "carpet tile", "modular carpet", "commercial flooring", "flooring manufacturer", "resilient flooring", "luxury vinyl tile", "lvt flooring", "office flooring", "corporate interiors", "commercial interiors", "sustainable flooring", "carbon neutral flooring", "recycled materials", "net zero", "design materials", "architectural interiors", "hospitality flooring", "education flooring", "healthcare flooring", "atlanta", "georgia"],
    "EVER": ["everquote", "everquote inc", "insurance marketplace", "online insurance", "auto insurance leads", "home insurance leads", "insurance comparison", "lead generation", "digital marketing", "customer acquisition", "insurance carriers", "policy quotes", "performance marketing", "fintech insurance", "cambridge", "massachusetts"],
    "CMRE": ["costamare", "costamare inc", "containership", "container shipping", "charter rates", "time charter", "shipping fleet", "vessels", "maritime shipping", "dry bulk", "shipping lessor", "charter contracts", "dividend", "shipping earnings", "fleet utilization", "monaco", "greece"],
    "SHOP": ["shopify", "shopify inc", "ecommerce platform", "online storefront", "merchant platform", "payments processing", "shopify payments", "point of sale", "shopify pos", "merchant solutions", "subscription revenue", "gross merchandise volume", "gmv", "checkout", "online retail software", "digital commerce", "small business tools", "merchant ecosystem", "tobi lutke", "ottawa", "canada"],
    "INS": ["intelligent systems corp", "intelligent systems corporation", "fintech", "payments processing", "electronic payments", "check processing", "checkalt", "national fleet services", "fleet cards", "fuel cards", "merchant services", "payment networks", "transaction processing", "financial technology", "bank payments", "norcross", "georgia", "ed heffernan"],
    "MG": ["magna", "magna international", "auto parts", "automotive supplier", "tier one supplier", "vehicle components", "oem supplier", "auto manufacturing", "tariffs", "trade policy", "usmca", "north america auto", "ev components", "electric vehicle supply chain", "canada manufacturing", "ontario", "graz"],
    "TIMB": ["timberland bancorp", "community bank", "regional bank", "banking", "loans", "deposits", "net interest margin", "dividend", "washington state"],
    "NTR": ["nutrien", "fertilizer", "potash", "nitrogen", "phosphate", "agriculture", "crop nutrients", "farm inputs", "canadian exporter", "tariffs", "trade policy", "usmca", "saskatchewan"],
    "EWC": ["ishares", "msci canada", "canada etf", "canadian equities", "country etf", "canada index", "tsx exposure"],
    "TD": ["toronto dominion", "td bank group", "canadian bank", "big five banks", "retail banking canada", "wealth management", "capital markets", "td securities", "net interest margin", "loan growth", "credit quality", "provisions for credit losses", "deposit growth", "earnings", "dividend", "stress test", "regulatory capital", "cet1", "canada us banking", "brian porter", "bharat masrani", "toronto"],
    "TRU": ["transunion inc", "credit data", "consumer credit data", "information services", "risk analytics", "identity verification", "earnings", "subscription revenue", "financial institutions", "regulatory compliance"],
    "FUTY": ["fidelity", "utilities etf", "utilities sector", "msci utilities", "dividend etf", "defensive sector", "interest rates", "yield"],
    "PAAS": ["pan american silver", "silver miner", "precious metals", "silver prices", "gold byproduct", "mining company", "latin america", "mexico", "peru", "bolivia", "argentina", "mining operations", "commodity exposure", "silver production", "gold production"],
    "SPMO": ["invesco", "s&p 500 momentum", "momentum factor", "momentum etf", "factor etf", "large cap momentum", "factor investing", "index etf", "portfolio allocation"],
    "DIVO": ["dividend etf", "income etf", "dividend income", "covered call", "dividend growth", "monthly income", "income portfolio", "yield strategy"],
    "QQQM": ["nasdaq 100", "growth etf", "large cap growth", "tech heavy etf", "index etf", "low expense ratio", "long term growth"],
    "BND": ["total bond market", "bond etf", "fixed income", "core bond holding", "vanguard bonds", "diversification", "interest rate exposure"],
    "VB": ["small cap etf", "us small cap", "vanguard small cap", "small cap exposure", "equity diversification", "long term allocation"],
    "CPA": ["copa holdings", "copa airlines", "airline", "latin america flights", "panama", "tocumen airport", "aviation", "passenger traffic", "air travel"],
    "TTD": ["the trade desk", "programmatic advertising", "digital advertising", "ad tech", "demand side platform", "dsp", "connected tv", "ctv advertising", "open internet", "uid2", "advertising software", "marketing technology", "jeff green"],
    "IBKR": ["interactive brokers", "brokerage", "trading platform", "stock broker", "etf transfers", "margin trading", "options trading", "global markets", "low commissions", "professional trading", "tax lot transfer"],
    "PETS": ["petmed express", "petmeds", "1-800-petmeds", "online pet pharmacy", "pet pharmacy", "prescription meds", "pet prescriptions", "flea and tick", "heartworm", "veterinarian", "rx", "delray beach", "florida", "marc puleo"],
    "AVUV": ["avuv", "avantis", "small cap value", "us small value", "value tilt", "factor investing", "size value", "scv", "etf", "expense ratio", "aum", "rebalancing", "vanguard", "vti", "vxus"],
    "SPLG": ["splg", "spdr", "state street", "s&p 500", "sp500", "index etf", "large cap", "passive investing", "expense ratio", "low cost", "cheaper voo", "core equity", "spdr portfolio"],
    "BCS": ["barclays", "uk bank", "london", "investment bank", "corporate banking", "credit cards", "trading desk", "fixed income", "rates trading", "c s venkatakrishnan", "venkat", "barclays research", "underweight", "overweight"],
    "IRBT": ["irobot", "roomba", "robot vacuum", "robot vac", "vacuum robot", "floor cleaning", "consumer robots", "home robotics", "smart home", "bedford", "massachusetts", "colin angle", "helen greiner", "rodney brooks", "chapter 11", "bankruptcy", "nasdaq delisting", "delisted"],
    "SMH": ["smh", "vaneck", "van eck", "semiconductor", "semis", "chip etf", "semiconductor etf", "mvis", "semiconductor index", "holdings", "expense ratio", "jan van eck", "new york", "nyc", "etf"],
    "RBC": ["royal bank of canada", "rbc bank", "toronto", "canada", "tsx", "nyse", "rbc gam", "global asset management", "mutual fund", "navf", "north american value", "life science", "technology fund", "canadian dividend", "us dividend", "rbf"],
    "GHM": ["graham corporation", "barber-nichols", "heliflow", "steam ejector", "surface condenser", "vacuum systems", "heat exchanger", "cryogenic pumps", "turbomachinery", "industrial products", "defense", "space", "batavia ny", "earnings", "guidance", "backlog", "bookings", "sec filing", "8-k"],
    "DXYZ": ["destiny tech100", "destiny etf", "private tech", "pre-ipo", "venture backed", "private companies", "late stage startups", "space x", "openai", "stripe", "bytedance", "net asset value", "nav discount", "premium to nav", "etf holdings", "portfolio weighting", "price vs nav", "asset value"],
    "FLO": ["flowers foods", "nature own", "wonder bread", "tastykake", "dave killer bread", "bakery products", "packaged foods", "consumer staples", "dividends", "dividend yield", "earnings", "guidance", "pricing power", "input costs", "labor costs", "distribution network", "branded bread"],
    "GME": ["gamestop", "video game retailer", "ryan cohen", "meme stock", "brick and mortar", "used games", "gaming accessories", "collectibles", "ecommerce pivot", "short interest", "short squeeze", "earnings", "cash on hand", "balance sheet", "store closures", "at-the-market offering", "sec filing"],
    "AMZN": ["amazon", "amazon.com", "aws", "amazon web services", "andy jassy", "jeff bezos", "seattle", "ecommerce", "cloud infrastructure", "hyperscaler", "data centers", "compute", "fulfillment centers", "logistics network", "last mile delivery", "advertising business", "free cash flow", "operating income", "earnings", "guidance", "sec filing"],
    "XEC": ["international", "ishares xec", "ishares emerging markets", "msci emerging markets", "emerging markets etf", "blackrock", "canada etf", "tsx listed", "brazil", "india", "china", "south korea", "taiwan", "international exposure", "diversification", "portfolio allocation", "long term hold", "index tracking", "emerging markets allocation"],
    "TIMB": ["timber pharmaceuticals", "biotechnology", "rare diseases", "orphan drug", "drug development", "clinical stage", "fda", "clinical trial", "phase 1", "phase 2", "drug pipeline", "lead candidate", "regulatory approval", "sec filing", "earnings", "cash runway", "capital raise", "nasdaq listed"],
    
}   

negative_context = {
    "OP": ["like op", "dear op"],
    "TIMB": ["dr tim", "tim holme", "tim cook", "named tim"],
    "LOT": ["lot of", "a lot of", "a lot", "parking lot", "lots of data"],
    "AMZN": ["amazing", "amazon rainforest", "jungle", "river amazon", "amazon prime day deals", "prime shipping", "online shopping", "buy on amazon", "ordered on amazon", "package delivery"],
    "BIG": ["big data", "big pharma", "big tech", "big companies", "big markets"],
    "RC": ["rc car", "rc cars", "rc toy", "rc toys"],
    "TGT": ["funds", "fund", "rates", "rate", "2030", "2025", "2026", "2027", "2028", "2029", "target price", "price target", "a buy target", "target asset allocation"],
    "UVV": ["basic", "income"],
    "BSE": ["sensex", "india"],
    "DBX": ["spread", "options", "box loom", "a box"],
    "DC": ["washington", "shooting", "national guard"],
    "CARE": ["healthcare", "health-care", "medical"],
    "GLP": ["glp", "glp-1", "glp-1 therapy", "glp-1 drugs", "glp-1 medications", "glp-1 treatments", "glp-1 insulin", "glp-1 drugs", "glp-1 medications", "glp-1 treatments", "glp-1 insulin"],
    "GES": ["what", "who", "when", "where", "why", "how", "i guess"],
    "AGI": ["ai", "scale laws"],
    "GDP": ["gross domestic product", "economy", "market", "cap", "Q1", "Q2", "Q3", "Q4"],
    "IT": ["information", "technology", "software", "hub", "india"],
    "EML": ["western", "us", "world", "grid", "east"],
    "BOE": ["BOE/d", "barrel of oil equivalent", "barrel of oil", "oil", "gas", "pipeline", "power generation", "utility"],
    "TLH": ["tax loss harvesting", "tax loss", "loss", "harvest", "harvesting", "tax", "losses", "losses", "losses"],
    "TACO": ["trump", "china", "trade", "tariff", "trade war", "trade agreement", "trade deal", "trade negotiations", "trade negotiations", "trade negotiations"],
    "OUT": ["out of the blue"],
    "BLUE": ["out of the blue"],
    "ABC": ["jimmy kimmel", "late night show", "late night", "tv"],
    "ASIC": ["asic", "mining", "hashrate", "hash", "hashpower", "hashrate", "hashpower", "hashrate", "hashpower", "rig"],
    "REE": ["projects", "earth", "mining"],
    "ATH": ["all time high", "all time low", "return to an ATH", "return to a ATH"],
    "SH": ["tarriffs"],
    "AWRE": ["i am aware", "i am", "be aware", "stay aware", "aware that"],
    "AG": ["basler"],
    "UP": ["came up", "going up"],
    "POOL": ["index", "class"],
    "BAND": ["memory", "bottleneck", "ai", "scaling laws", "latency", "reliability"],
    "BAL": ["balanced fund", "dodge cox", "dodge & cox", "dodgex", "dodgx", "vanguard target", "target date", "fund investment"],
    "ON": ["trump on", "on china", "on tariffs", "on trade", "on inflation", "on immigration", "on iran", "on russia", "on ukraine", "on the", "on monday", "on tuesday", "on wednesday", "on thursday", "on friday"],
    "HBM": ["high bandwidth memory", "ai memory", "dram", "gpu memory", "memory demand", "hbm demand"],
    "CD": ["certificate of deposit", "cd account", "cd accounts", "savings", "interest rate", "apy", "bank", "fdic", "ira", "in a cd"],
    "HYS": ["high yield savings", "hys account", "savings account", "apy", "interest rate", "bank", "cit", "fdic", "direct deposit"],
    "CIT": ["cit bank", "savings account", "high yield savings", "hys", "apy", "interest rate", "fdic", "online bank", "direct deposit"],
    "SOL": ["shit out of luck", "out of luck", "am i sol?", "am i sol", "would i be sol?", "would i be sol"],
    "ACH": ["ach transfer", "ach payment", "ach trace", "trace number", "bank transfer", "routing number", "account number", "left my bank"],
    "OCC": ["office of the comptroller", "comptroller of the currency", "bank regulator", "regulatory complaint", "filed a complaint", "bbb", "ftc", "attorney general"],
    "EDIT": ["edit -", "edit:"],
    "HR": ["hr requests", "hr related requests","human resources", "hr department", "hr manager", "hr director", "hr team", "hr policies", "hr procedures", "hr benefits", "hr compensation", "hr training", "hr recruitment", "hr retention", "employee relations", "employee engagement", "employee turnover"],
    "NICE": ["nice dinner", "nice gesture", "nice to meet you", "nice to have"],
    "FTC": ["federal trade commission", "consumer complaint", "filed a complaint", "bbb", "attorney general", "regulator", "antitrust"],
    "EVER": ["NEVER"],
    "CMRE": ["collections", "collection agency", "medical bill", "hospital bill", "appeal process", "debt", "billing"],
    "SHOP": ["shop around", "shopping", "local shop", "repair shop", "auto shop", "coffee shop", "small shop", "own a shop", "went to a shop", "in town shop", "brick and mortar", "retail store", "heloc", "loan shopping"],
    "SLAM": ["slam markets", "markets slam", "stocks slam", "shares slam", "prices slam", "slam economy", "slam growth", "slam outlook"],
    "AAA": ["credit rating", "rating", "moodys", "moody’s", "s&p", "fitch", "downgrade", "outlook", "sovereign debt", "treasury"],
    "AA": ["credit rating", "rating", "moodys", "moody’s", "s&p", "fitch", "downgrade", "outlook", "sovereign debt", "treasury"],
    "MG": ["milligram", "mg dosage", "medication", "supplement"],
    "TIMB": ["senator tim", "tim kaine", "tim cook", "tim berners lee", "timothy", "named tim", "my friend tim"],
    "V": ["visa gift card", "gift card", "prepaid card", "balance check", "card activation", "card declined", "present", "christmas gift", "mr."],
    "SAT": ["sat score", "gpa", "ib", "stats", "ecs"],
    "TRU": ["transunion", "credit report", "credit bureau", "credit dispute", "dispute", "freeze", "fraud alert", "credit score", "credit file"],
    "CPA": ["im a CPA","certified public accountant", "accountant", "accounting", "audit", "auditing", "tax", "taxes", "financial reporting", "public accounting", "big four", "ipo reporting", "cpa exam", "license"],
    "TR": ["trade republic", "broker", "brokerage app", "etf transfer", "account transfer", "investment app", "german broker", "european broker"],
    "GDP": ["us gdp", "gdp data", "gdp forecast", "gdp growth forecast"],
    "AR": ["annual report", "-ar.pdf", "10-k", "pdf", "report"],
    "MAG": ["mag 7", "magnificent seven", "mag7", "mag 6", "mag6", "mag 5", "mag5", "mega cap tech", "big tech", "tech giants", "faang"],
    "BETA": ["volatility", "market beta", "high beta", "low beta", "beta exposure", "beta risk", "portfolio beta", "roe"],
    "SMA": ["moving average", "simple moving average", "50 day", "200 day", "technical indicator", "chart", "trend line", "roe"],
    "PEG": ["peg ratio", "price earnings growth", "valuation", "eps", "p/e", "sales q/q", "roa", "roe"],
    "GHM": ["benjamin graham", "intelligent investor"],
    "DCF": ["dcf model", "dcf valuation"],
    "SRT": ["significant risk transfer", "synthetic risk transfer", "srt exposures", "srt structures", "securitization", "tranche", "credit risk transfer", "crt", "risk transfer", "regulatory capital", "basel", "rwa", "risk weighted assets"],
    "PETS": ["express our", "thanks", "my pets", "pet owner", "dog", "cat", "puppy", "kitten", "adoption", "vet bill", "animal shelter", "pet insurance", "pet food", "pet supplies", "pet store", "pet sitter", "pet sitting", "grooming", "walk my dog"],
    "FAT": ["a fat one", "super fat", "fat payout", "fat earnings", "fat year"],
    "CRS": ["central reservation system", "reservation system", "hotel booking", "hotel reservations", "property management system", "pms", "hospitality", "gatekeeper", "direct booking", "channel manager", "ota", "gds", "booking engine", "inventory", "rates"],
    "SF": ["san francisco", "chronicle", "sf chronicle", "sf bay area"],
    "CAPE": ["shiller", "shiller cape", "cape ratio", "cyclically adjusted", "price earnings", "valuation", "market valuation", "s&p 500 valuation", "10x", "overvalued", "undervalued"],
    "ARVL": ["arrival of", "the arrival"],
    "BB": ["bb grade", "bb+", "bb-", "junk", "speculative grade", "high yield", "credit rating", "ratings", "moody", "s&p", "fitch", "investment grade", "downgrade", "spread", "yield"],
    "U": ["u.s.", "u.s. dividend"],
    "DO": ["i do", "do you", ],
    "GHM": ["benjamin graham", "graham and dodd", "security analysis", "value investing", "the intelligent investor", "graham number", "graham formula", "margin of safety", "graham cracker", "graham scan", "cfa curriculum"],
}

