"""Centralized ticker context keywords and disambiguation helpers."""

ticker_context = {
    "A": ["agilent", "lab equipment", "chromatography", "analytical instruments", "keysight spinoff"],
    "B": ["barnes group", "aerospace machining", "mro"],
    "C": ["citigroup", "citi", "consumer banking", "investment bank"],
    "D": ["dominion", "utility", "power generation", "natural gas", "pipeline"],
    "E": ["eni", "italian energy", "oil", "gas"],
    "F": ["ford", "f-150", "mustang", "bronco", "detroit auto"],
    "G": ["genpact", "bpo", "business process", "outsourcing"],
    "H": ["hyatt", "hotel", "hospitality", "lodging"],
    "K": ["kellogg", "kellanova", "cereal", "snacks"],
    "L": ["loews", "conglomerate", "insurance", "pipeline"],
    "M": ["macys", "department store", "retail"],
    "O": ["realty income", "reit", "monthly dividend", "triple net"],
    "R": ["ryder", "truck rental", "logistics", "fleet management"],
    "T": ["at&t", "wireless", "fiber", "telecom"],
    "U": ["unity", "game engine", "monetization", "runtime"],
    "X": ["us steel", "steelmaker", "hot rolled", "steel industry"],
    "AC": ["air canada", "canadian airline", "toronto", "montreal", "vancouver"],
    "AAPL": ["apple", "iphone", "ipad", "mac", "macbook", "ipad pro"],
    "ADBE": ["adobe", "creative cloud", "digital media", "subscription", "generative ai"],
    "ADP": ["automatic data processing", "payroll", "hr software"],
    "AEO": ["american eagle", "apparel", "teen fashion", "mall retail", "denim"],
    "ALAB": ["astera labs", "cxl", "ai networking", "pcie"],
    "ANET": ["arista", "networking", "switches", "datacenter", "ethernet", "ai infrastructure"],
    "ANF": ["abercrombie", "fitch", "retail", "mall retail", "turnaround", "denim"],
    "APLD": ["applied digital", "data centers", "hpc", "ai hosting", "colocation"],
    "ASTS": ["ast spacemobile", "satellite", "direct to device", "space-based cellular", "telecom partnerships"],
    "AVGO": ["broadcom", "semiconductors", "chips", "ai accelerators", "custom silicon", "networking hardware", "data center"],
    "BA": ["boeing", "aerospace", "defense", "commercial aviation", "launch systems"],
    "BABA": ["alibaba", "china ecommerce", "hangzhou", "ali cloud", "jack ma"],
    "BE": ["bloom energy", "fuel cell", "solid oxide", "power server", "hydrogen"],
    "BK": ["bk technologies", "land mobile radios", "defense communications", "insider ownership"],
    "BILI": ["bilibili", "china streaming", "anime", "video platform"],
    "BEST": ["best inc", "best logistics", "china logistics", "delivery services"],
    "BMNR": ["ethereum", "validator network", "staking", "tokenization"],
    "BUD": ["anheuser", "inbev", "budweiser", "beer", "alcohol", "beverage", "beyond beer", "beatbox"],
    "CLS": ["celestica", "electronics manufacturing", "contract manufacturing", "hardware services"],
    "CORZ": ["core scientific", "bitcoin mining", "data centers", "hosting", "hash rate"],
    "CRWD": ["crowdstrike", "endpoint", "falcon", "cybersecurity", "edr", "xdr", "threat hunting"],
    "CVNA": ["carvana", "used cars", "online auto sales", "auto ecommerce", "subprime loans", "inventory", "vending machine"],
    "DASH": ["doordash", "delivery", "food delivery", "courier", "dashpass", "ubereats", "grubhub", "restaurant delivery"],
    "DBX": ["dropbox", "cloud storage", "file sync", "saas"],
    "DKNG": ["draftkings", "sports betting", "gambling"],
    "DLTR": ["dollar tree", "discount retailer", "value chain"],
    "DNOW": ["distributionnow", "oilfield services", "industrial distribution", "energy equipment"],
    "EDU": ["new oriental", "education", "china tutoring"],
    "EDIT": ["editas", "gene editing", "crispr", "biotech"],
    "ESNT": ["essent", "mortgage insurance", "private mortgage", "bermuda", "home loans"],
    "EVTL": ["vertical aerospace", "evtol", "electric aviation", "urban air mobility"],
    "FIGR": ["figure technologies", "blockchain lending", "mortgage tech", "tokenization", "provenance"],
    "FLNC": ["fluence energy", "energy storage", "grid software", "battery systems"],
    "FLWS": ["1-800-flowers", "gifting", "ecommerce", "floral delivery", "seasonal demand"],
    "FLOT": ["floating rate", "bond etf", "treasury", "investment grade", "short term bond"],
    "GME": ["gamestop", "ryan cohen", "stonks", "moass", "retail trader"],
    "GOOG": ["google", "alphabet", "search", "youtube", "gemini"],
    "GOLD": ["barrick", "barrick gold", "mining", "ounces", "commodity","goldcorp", "newmont"],
    "GS": ["goldman sachs", "investment banking", "research notes", "macro outlook"],
    "HOOD": ["robinhood", "brokerage", "trading app", "vlad tenev"],
    "HSBC": ["hsbc", "global bank", "international banking", "wealth management"],
    "IBM": ["ibm", "quantum computing", "enterprise software", "hardware systems"],
    "IBIT": ["blackrock", "bitcoin etf", "spot bitcoin", "crypto fund"],
    "IP": ["international paper", "pulp", "packaging", "paper products"],
    "IMO": ["imperial oil", "oil sands", "upstream", "refining", "canadian energy"],
    "IOVA": ["iova", "biotech", "til therapy", "lifileucel", "melanoma","cell therapy", "oncology"],
    "IREN": ["iris energy", "bitcoin miner", "data center", "ai infrastructure"],
    "IWM": ["russell 2000", "small cap etf", "market breadth", "small cap rally"],
    "JPM": ["jpmorgan", "banking", "balance sheet", "asset management", "investment bank"],
    "KEX": ["kirby corporation", "barge", "inland marine", "tugboat", "marine transportation", "petrochemical transport"],
    "KRMN": ["karman", "aerospace manufacturing", "defense contracting", "hypersonics"],
    "KSS": ["kohls", "department store", "apparel", "inventory", "promotions"],
    "LLY": ["eli lilly", "mounjaro", "zepbound", "pharma", "weight loss drug"],
    "LMT": ["lockheed martin", "defense", "prime contractor", "missile systems", "space launch"],
    "LSEG": ["london stock exchange", "exchange group", "ftse owner"],
    "LUNR": ["intuitive machines", "lunar", "moon mission", "nasa contracts", "lunar lander"],
    "LVMH": ["louis vuitton", "moet hennessy", "bernard arnault", "luxury conglomerate"],
    "META": ["meta", "facebook", "instagram", "whatsapp", "oculus", "vr", "metaverse", "threads", "zuck", "zuckerberg"],
    "MRVL": ["marvell", "semiconductors", "data center chips", "networking silicon", "ai accelerators"],
    "MSCI": ["index provider", "benchmark", "indices"],
    "MSFT": ["microsoft", "azure", "cloud computing", "windows", "xbox", "copilot", "nadella", "enterprise software", "ai chips", "dynamics 365"],
    "MSTR": ["microstrategy", "michael saylor", "bitcoin", "btc treasury", "convertible notes"],
    "MT": ["arcelormittal", "steel", "iron ore", "steel mills", "trade tariffs"],
    "MYRG": ["myr group", "electrical contracting", "grid infrastructure"],
    "NTDOY": ["nintendo", "gaming", "console", "wii", "switch", "zelda", "pokemon", "mario", "nintendo switch", "kirby"],
    "NBIS": ["nasdaq biotech etf", "biotech exposure", "clinical pipeline", "healthcare sector"],
    "NEE": ["nextera", "utility", "renewable energy", "florida power", "fpl"],
    "NICE": ["nice ltd", "enterprise software", "cloud transition", "financial compliance"],
    "NKE": ["nike", "footwear", "athletic apparel", "sneakers", "endorsements"],
    "NQ": ["nasdaq futures", "e-mini", "index futures", "/nq", "nasdaq 100"],
    "NUE": ["nucor", "steel", "electric arc furnace", "infrastructure spending"],
    "NVDA": ["nvidia", "geforce", "rtx", "cuda", "gpu", "jensen", "chips", "semiconductor", "data center", "taiwan"],
    "NXXT": ["microgrids", "distributed energy", "localized grid"],
    "OKLO": ["nuclear", "microreactor", "oklo"],
    "ORCL": ["oracle", "cloud infrastructure", "oci", "database", "enterprise software"],
    "PATH": ["uipath", "automation", "rpa", "robotic process automation", "maestro"],
    "PDD": ["pinduoduo", "temu", "china ecommerce"],
    "PHYS": ["sprott", "gold trust"],
    "PL": ["planet labs", "earth imaging", "satellites", "geospatial data", "analytics"],
    "PLD": ["prologis", "reit", "logistics", "warehouses"],
    "PPSI": ["pioneer power", "microgrids", "distributed infrastructure"],
    "QQQ": ["nasdaq 100", "tech index", "nasdaq"],
    "RBC": ["royal bank of canada", "wealth management", "capital markets"],
    "SWCH": ["switch inc", "data centers", "colocation", "prime data centers"],
    "RGTI": ["rigetti", "quantum", "kulkarni", "rigetti computing"],
    "RGTZ": ["rigetti", "inverse", "quantum"],
    "RKLB": ["rocket lab", "launch", "electron rocket", "neutron", "space missions"],
    "SEZL": ["sezzle", "bnpl", "installments", "credit", "buy now pay later"],
    "SGOV": ["t bill", "treasury etf", "short term treasury", "government bond", "cash alternative"],
    "SMR": ["small modular reactor", "nuclear"],
    "SOND": ["sonder", "hospitality", "lodging"],
    "SPY": ["s&p 500", "index fund", "sp500", "benchmark", "market index", "large cap", "passive investing", "expense ratio"],
    "TAL": ["tal education", "tutoring", "china education", "edtech"],
    "TQQQ": ["3x leveraged etf", "nasdaq 100 leverage", "daily reset", "volatility"],
    "TISI": ["team inc", "industrial services", "maintenance", "inspection", "repair"],
    "TSLA": ["tesla", "elon", "musk", "gigafactory", "autopilot", "cybertruck", "model 3", "model y", "full self driving"],
    "URBN": ["urban outfitters", "anthropologie", "free people", "fashion", "retail"],
    "URA": ["uranium etf", "miners"],
    "UUUU": ["energy fuels", "uranium", "rare earths"],
    "VEQT": ["vanguard all equity", "all equity etf", "veqt.to"],
    "VGSH": ["vanguard", "short term treasury", "treasury etf", "bond fund"],
    "VHYG": ["vanguard usd", "corporate bond", "high yield bond", "vhyg.l"],
    "VOO": ["s&p 500 exposure", "vanguard etf", "low expense ratio", "passive"],
    "VRT": ["vertiv", "data center infrastructure", "thermal management", "power systems"],
    "VTI": ["total stock market", "broad market etf", "vanguard", "low expense ratio"],
    "VXUS": ["vanguard international", "ex-us", "international equities", "global diversification"],
    "WB": ["weibo", "china social media", "microblog"],
    "WBD": ["warner", "discovery", "hbo", "max", "netflix", "studio deal", "streaming", "content distribution"],
    "WSR": ["whitestone reit", "shopping centers", "retail reit", "houston", "phoenix"],
    "WRBY": ["warby parker", "eyeglasses", "eyewear", "direct to consumer", "vision care"],
    "DRIP": ["direxion", "oil", "etf" "oil futures"],
    "TLN": ["talen energy corp", "natural gas", "pipeline", "power generation", "utility"],
    "RSI": ["rush street interactive", "gambling", "casino", "sports betting", "online gaming", "bet rivers", "rush bet", "rushbet.co", "sugarhouse"],
}

# Keywords that strongly indicate the uppercase token is NOT a ticker.
CONTEXT_BLACKLIST = {
    "CEO": ["executive", "leadership", "position", "company", "hiring"],
    "FDA": ["approval", "regulator", "drug", "clinical", "therapy"],
    "BNPL": ["buy now pay later", "fintech", "payments", "service"],
    "USD": ["dollar", "forex", "currency", "fx", "macro"],
    "WSB": ["subreddit", "reddit", "community", "mods"],
    "SPAC": ["blank check", "shell company", "acquisition vehicle", "special purpose"],
    "ARPU": ["average revenue per user", "metric", "kpi"],
    "NYSE": ["exchange", "trading floor", "listing", "market open"],
    "FTSE": ["index", "ftse 100", "ftse 250"],
    "CNBC": ["tv", "anchor", "interview", "network"],
    "ADP": ["jobs report", "employment report", "labor market", "private employers","payroll data", "adp numbers", "jobs data"],
    "BETA": ["high beta", "low beta", "market beta", "portfolio beta", "beta exposure", "beta risk", "beta adjustment"],
}

